# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'studiosol_teste' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for studiosol_teste
  
  pod "Apollo"
  pod "Apollo/SQLite"
  pod "Apollo/WebSocket"

end
